# The URL the site will be built for
base_url = "https://kummatty.yali.fi"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library

build_search_index = false

theme = "lightspeed"

sort_by = "date"

title = "‡¥ï‡µÅ‡¥Æ‡µç‡¥Æ‡¥æ‡¥ü‡µç‡¥ü‡¥ø ‡¥™‡µç‡¥∞‡µã‡¥ú‡¥ï‡µç‡¥ü‡µç"
description = "‡¥ï‡¥æ‡¥¥‡µç‡¥ö‡¥ï‡µæ, ‡¥ï‡µÜ‡¥ü‡µç‡¥ü‡µÅ‡¥ï‡¥æ‡¥¥‡µç‡¥ö‡¥ï‡µæ ‡¥ï‡¥æ‡¥¥‡µç‡¥ö‡¥™‡µç‡¥™‡¥æ‡¥ü‡µÅ‡¥ï‡µæ"
minify_html = true
generate_feed = true
feed_filename = "atom.xml"
default_language = "ml"

taxonomies = [
    {name = "‡¥≤‡¥ø‡¥∏‡µç‡¥±‡µç‡¥±‡µç", feed = true}, # each tag will have its own feed
    {name = "‡¥§‡¥∞‡¥Ç", paginate_by = 10, feed = true},  # ‡¥∏‡¥ø‡¥®‡¥ø‡¥Æ, ‡¥∏‡µÄ‡¥∞‡¥ø‡¥Ø‡µΩ, ‡¥®‡¥æ‡¥ü‡¥ï‡¥Ç, ‡¥™‡¥æ‡¥ü‡µç‡¥ü‡µÅ‡µç ‡¥é‡¥®‡µç‡¥®‡¥ø‡¥ô‡µç‡¥ô‡¥®‡µÜ ‡¥é‡¥®‡µç‡¥§‡µÅ‡¥Æ‡¥æ‡¥ï‡¥æ‡¥Ç.
    {name = "‡¥°‡¥Ø‡¥±‡¥ï‡µç‡¥ü‡µº", feed = true, paginate_by = 10},
    {name = "‡¥¥‡¥æ‡µ∫‡¥¥‡µá", feed = true, paginate_by = 10},
    {name = "‡¥Ö‡¥µ‡¥æ‡µº‡¥°‡µÅ‡¥ï‡µæ", feed = true, paginate_by = 10},
    {name = "‡¥±‡¥ø‡¥≤‡µÄ‡¥∏‡µç ‡¥ö‡µÜ‡¥Ø‡µç‡¥§ ‡¥µ‡µº‡¥∑‡¥Ç", feed = true, paginate_by = 10},
    {name = "‡¥ï‡¥•‡¥æ‡¥ï‡µÉ‡¥§‡µç‡¥§‡µç", feed = true, paginate_by = 10},
    {name = "‡¥§‡¥ø‡¥∞‡¥ï‡µç‡¥ï‡¥•", feed = true, paginate_by = 10},
    {name = "‡¥∏‡¥Ç‡¥≠‡¥æ‡¥∑‡¥£‡¥Ç", feed = true, paginate_by = 10},
    {name = "‡¥∏‡¥Ç‡¥ó‡µÄ‡¥§‡¥Ç", feed = true, paginate_by = 10},
    {name = "‡¥õ‡¥æ‡¥Ø‡¥æ‡¥ó‡µç‡¥∞‡¥π‡¥£‡¥Ç", feed = true, paginate_by = 10},
    {name = "‡¥é‡¥°‡¥ø‡¥±‡µç‡¥±‡µº", feed = true, paginate_by = 10},
    {name = "‡¥≤‡¥æ‡¥¨‡µç", feed = true, paginate_by = 10},
    {name = "‡¥∂‡¥¨‡µç‡¥¶‡¥≤‡µá‡¥ñ‡¥®‡¥Ç", feed = true, paginate_by = 10},
    {name = "‡¥®‡¥ø‡µº‡¥Æ‡µç‡¥Æ‡¥æ‡¥§‡¥æ‡¥µ‡µç", feed = true, paginate_by = 10},
    {name = "director", feed = true, paginate_by = 10},
]

highlight_code = true
highlight_theme = "base16-ocean-dark"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true
lazy_async_image = true

[slugify]
paths = "safe"
taxonomies = "on"
anchors = "on"
# Whether to remove date prefixes for page path slugs.
# For example, content/posts/2016-10-08_a-post-with-dates.md => posts/a-post-with-dates
# When true, content/posts/2016-10-08_a-post-with-dates.md => posts/2016-10-08-a-post-with-dates
paths_keep_dates = false



[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

footer_links = [
    {url = "$BASE_URL/en", name = "üá™ En "},
    {url = "$BASE_URL/about", name = "üëãüèΩ ‡¥π‡¥≤‡µã"},
    {url = "$BASE_URL/atom.xml", name = "üóÇ RSS"},
    {url = "https://t.me/KummattyTheatre", name = "‚úàÔ∏è ‡¥ö‡µº‡¥ö‡µç‡¥ö‡¥ï‡µæ"},
    {url = "https://www.instagram.com/kummattyproject", name = "üì∏ ‡¥™‡µá‡¥ú‡µç"},
]
ogimage = "/images/Kummatty.jpg"
author = "@moolekkari"
zola = false
netlify = false
maintained_with_love = false

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the path of the page/section in the index
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true
index_format = "elasticlunr_javascript"

[translations]

# Additional languages definition
# You can define language specific config values and translations: 
# title, description, generate_feed, feed_filename, taxonomies, build_search_index
# as well as its own search configuration and translations (see above for details on those)
[languages]
# For example
[languages.en]
title = "The Kummatty Project"
description = "Movies, Theatres, Narratives and Ways of seeing"
generate_feed = true
build_search_index = true
taxonomies = [
    {name = "tags", feed = true}, # each tag will have its own feed
    {name = "list", feed = true}, # each tag will have its own feed
    {name = "director", feed = true, paginate_by = 10},
    {name = "type", paginate_by = 10, feed = true},  # ‡¥∏‡¥ø‡¥®‡¥ø‡¥Æ, ‡¥∏‡µÄ‡¥∞‡¥ø‡¥Ø‡µΩ, ‡¥®‡¥æ‡¥ü‡¥ï‡¥Ç, ‡¥™‡¥æ‡¥ü‡µç‡¥ü‡µÅ‡µç ‡¥é‡¥®‡µç‡¥®‡¥ø‡¥ô‡µç‡¥ô‡¥®‡µÜ ‡¥é‡¥®‡µç‡¥§‡µÅ‡¥Æ‡¥æ‡¥ï‡¥æ‡¥Ç.
    {name = "genre", feed = true, paginate_by = 10},
    {name = "awards", feed = true, paginate_by = 10},
    {name = "release year", feed = true, paginate_by = 10},
    {name = "writer", feed = true, paginate_by = 10},
    {name = "script", feed = true, paginate_by = 10},
    {name = "dialogue", feed = true, paginate_by = 10},
    {name = "music", feed = true, paginate_by = 10},
    {name = "cinematography", feed = true, paginate_by = 10},
    {name = "editor", feed = true, paginate_by = 10},
    {name = "lab", feed = true, paginate_by = 10},
    {name = "sound", feed = true, paginate_by = 10},
    {name = "producer", feed = true, paginate_by = 10},
]
